added Views class (abstract and implementation)
Countly/countly-sdk-flutter-bridge pull request #119
Opened 2023-07-16 13:52 UTC by peterBrxwn

2023-07-17 09:51 UTC, ArtursKadikis requested changes
segmentation values are optional for start/stop. not nullable

2023-07-17 09:51 UTC, ArtursKadikis commented on lib/views.dart
> +  void stopLastView();
for now not needed

2023-07-17 09:51 UTC, ArtursKadikis commented on lib/countly_config.dart
> +  CountlyConfig enableAutomaticViewTracking() {
not needed

2023-07-17 09:51 UTC, ArtursKadikis commented on lib/countly_config.dart
> +  CountlyConfig enableGlobalViewSegmentation() {
wrong name and function

2023-07-17 09:51 UTC, ArtursKadikis commented on lib/countly_config.dart
> +  bool _automaticViewTracking = false;
not all fields are needed

2023-07-20 09:07 UTC, peterBrxwn commented
> segmentation values are optional for start/stop. not nullable

If the values are optional, it means the must be nullable (because if the are not passed, then their value is null)

2023-07-20 10:13 UTC, ArtursKadikis requested changes
Start adding the native side

2023-07-20 10:13 UTC, ArtursKadikis commented on lib/countly_config.dart
> +  bool get globalViewSegmentation => _globalViewSegmentation;
it's not a boolean

2023-07-20 10:13 UTC, ArtursKadikis commented on lib/countly_config.dart
> +  CountlyConfig setGlobalViewSegmentation() {
it takes a map from string to object

2023-08-03 09:44 UTC, ArtursKadikis requested changes
"useMultipleViewFlow"
deprecate more old calls

"views_pauseViewWithID" -> "[Views] pauseViewWithID"

"startViewSegmentation" -> "startViewWithSegmentation"

2023-08-03 09:44 UTC, ArtursKadikis requested changes
"useMultipleViewFlow"
deprecate more old calls

"views_pauseViewWithID" -> "[Views] pauseViewWithID"

"startViewSegmentation" -> "startViewWithSegmentation"

2023-08-31 14:00 UTC, merged