Relative path
Countly/countly-sdk-flutter-bridge pull request #178
Opened 2023-12-19 21:02 UTC by peterBrxwn

2023-12-19 21:04 UTC, peterBrxwn commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Flutter] Change all imports to relative imports](https://trello.com/c/o4jkilLB/1175-flutter-change-all-imports-to-relative-imports)

2023-12-20 05:48 UTC, turtledreams commented
actual pr
![image](https://github.com/Countly/countly-sdk-flutter-bridge/assets/62231246/38e0c0a7-be74-4d39-99e0-5fc0aaa4daec)

2023-12-20 06:33 UTC, turtledreams requested changes
lets change the paths in files at src folder too. they should import from inside the src

2023-12-21 12:59 UTC, turtledreams approved these changes

2024-01-02 11:32 UTC, merged