fixed all async bug
Countly/countly-sdk-flutter-bridge pull request #209
Opened 2024-03-13 15:41 UTC by peterBrxwn

2024-03-13 15:43 UTC, peterBrxwn commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Flutter] Check native level code and make sure we always "return"](https://trello.com/c/DQgqsR0D/1570-flutter-check-native-level-code-and-make-sure-we-always-return)

2024-03-14 07:12 UTC, arifBurakDemiray approved these changes
Seems okey, all not-return funcs have return except throwNativeException

2024-03-15 07:58 UTC, turtledreams approved these changes

2024-03-15 07:59 UTC, turtledreams commented
android side is all cool rite?

2024-03-15 12:02 UTC, ArtursKadikis requested changes
test all calls

2024-03-18 14:25 UTC, peterBrxwn commented
@ArtursKadikis finished testing all calls.

2024-03-19 08:45 UTC, turtledreams requested changes

2024-03-19 08:45 UTC, turtledreams commented on lib/src/countly_flutter.dart
> -      onNotification(callback);
lets talk about this

2024-03-19 11:44 UTC, turtledreams commented on lib/src/countly_flutter.dart
> -      onNotification(callback);
also test this peter with multiople push notifications and such https://countly.getoutline.com/doc/push-notifications-9qHAFIWhlc

2024-03-21 06:41 UTC, ijunaid approved these changes

2024-03-21 10:40 UTC, turtledreams commented on lib/src/countly_flutter.dart
> -      onNotification(callback);
@peterBrxwn did you?

2024-04-02 08:51 UTC, ArtursKadikis approved these changes

2024-04-02 08:52 UTC, turtledreams approved these changes

2024-04-02 08:52 UTC, merged