fixed fatal error bug
Countly/countly-sdk-flutter-bridge pull request #211
Opened 2024-03-15 11:13 UTC by peterBrxwn

2024-03-15 11:14 UTC, peterBrxwn commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Flutter] Fix logException "nonfatal" and segmentation problem](https://trello.com/c/THaw2LAB/1583-flutter-fix-logexception-nonfatal-and-segmentation-problem)

2024-03-15 12:17 UTC, ArtursKadikis requested changes
Check out also the ios side

2024-03-19 09:54 UTC, peterBrxwn commented
@ArtursKadikis done

2024-03-20 12:13 UTC, turtledreams requested changes

2024-03-20 12:13 UTC, turtledreams commented on CHANGELOG.md
>  ## xx.x.x
lets also add an entry about ios changes

2024-03-21 10:36 UTC, turtledreams approved these changes

2024-03-21 10:37 UTC, turtledreams commented
we will have to add a test for this in a diffrent pr

2024-03-22 10:42 UTC, ijunaid approved these changes

2024-03-22 11:10 UTC, merged