single line stack trace
Countly/countly-sdk-flutter-bridge pull request #273
Opened 2024-08-14 15:28 UTC by peterBrxwn

This PR resolves an issue where the stack trace on the server was not properly recognized due to double newlines. The fix standardizes it to a single newline for correct processing.

2024-08-14 15:29 UTC, peterBrxwn commented
![](https://github.trello.services/images/mini-trello-icon.png) [[flutter] Single Line stack trace](https://trello.com/c/w2rEbkX8/1946-flutter-single-line-stack-trace)

2024-08-15 06:35 UTC, arifBurakDemiray approved these changes

2024-08-20 08:38 UTC, AliRKat approved these changes

2024-08-20 12:21 UTC, turtledreams requested changes
needs a changelog peter-san.

2024-08-22 06:19 UTC, turtledreams approved these changes

2024-08-22 06:19 UTC, merged