[SDK-618] - setUserLocation call added with all parameters of location.
Countly/countly-sdk-flutter-bridge pull request #57
Opened 2022-02-08 15:51 UTC by ijunaid

-- Fix warnings and remove deprecated calls from examples App.
-- Updated underlying android SDK to 21.11.0-RC4

2022-02-08 19:07 UTC, ArtursKadikis requested changes
this PR has your server credentials.

2022-02-08 19:07 UTC, ArtursKadikis commented on lib/countly_flutter.dart
> +        '$exceptionString\n\n$stacktrace', nonfatal, segmentation);
is this correct?

2022-02-08 19:07 UTC, ArtursKadikis commented on ios/Classes/CountlyFlutterPlugin.m
> +                    location = (CLLocationCoordinate2D){latitudeDouble,longitudeDouble};
What happens if you pass:
",10" or "10,"?

2022-02-09 12:17 UTC, ArtursKadikis requested changes

2022-02-09 12:17 UTC, ArtursKadikis commented on ios/Classes/CountlyFlutterPlugin.m
> +
we need 2 warnings for each of the value

2022-02-09 12:17 UTC, ArtursKadikis commented on ios/Classes/CountlyFlutterPlugin.m
> +
add also a third warning in case array has more values

2022-02-09 12:17 UTC, ArtursKadikis commented on ios/Classes/CountlyFlutterPlugin.m
> +            if(gpsCoordinates && [gpsCoordinates containsString:@","]){
the lack of a comma should be communicated. Print error

2022-02-09 12:17 UTC, ArtursKadikis commented on ios/Classes/CountlyFlutterPlugin.m
> +                    double longitudeDouble = [longitudeString doubleValue];
after this line. If any of the location values are 0, print warning of potential error and location string

2022-02-09 12:21 UTC, ArtursKadikis commented on ios/Classes/CountlyFlutterPlugin.m
> +
skip the "empty string" warning

2022-02-09 13:15 UTC, ijunaid commented on lib/countly_flutter.dart
> +        '$exceptionString\n\n$stacktrace', nonfatal, segmentation);
yes, it is correct.

2022-02-10 14:47 UTC, ArtursKadikis requested changes

2022-02-10 14:47 UTC, ArtursKadikis commented on example/ios/Flutter/Flutter.podspec
> +  s.ios.deployment_target = '9.0'
this should be reverted

2022-02-10 14:47 UTC, ArtursKadikis commented on CHANGELOG.md
> +* Added "setUserLocation" method to set user location
Mention that the old call was deprecated

2022-02-10 14:47 UTC, ArtursKadikis commented on CHANGELOG.md
> +* Added "setUserLocation" method to set user location
and also mention the old initLocation call

2022-02-10 14:47 UTC, ArtursKadikis commented on CHANGELOG.md
> +* Added "setUserLocation" method to set user location
"Deprecated old init config methods. You should use the config object now. Those methods are: ..."

2022-02-10 14:47 UTC, ArtursKadikis commented on lib/countly_flutter.dart
> +  /// Set user location
mention that all parameters are optional, but at least one has to be set

2022-02-10 14:47 UTC, ArtursKadikis commented on ios/Classes/CountlyFlutterPlugin.m
> +             NSString* gpsCoordinates = location[@"gpsCoordinates"];
empty space "typo"

2022-02-10 14:47 UTC, ArtursKadikis commented on ios/Classes/CountlyFlutterPlugin.m
> +                        COUNTLY_FLUTTER_LOG(@"Invalid location Coordinates: '%@'", gpsCoordinates);
wrap the exception in "[ ]"

2022-02-10 14:47 UTC, ArtursKadikis commented on ios/Classes/CountlyFlutterPlugin.m
> +                        COUNTLY_FLUTTER_LOG(@"Invalid location Coordinates: '%@'", gpsCoordinates);
remove empty space

2022-02-10 14:47 UTC, ArtursKadikis commented on ios/Classes/CountlyFlutterPlugin.m
> +                            COUNTLY_FLUTTER_LOG(@"Invalid location Coordinates: '%@', it should contains two comma seperated double values", gpsCoordinates);
this warning needs to be reworked

2022-02-10 14:47 UTC, ArtursKadikis commented on ios/Classes/CountlyFlutterPlugin.m
> +                            COUNTLY_FLUTTER_LOG(@"Invalid location Coordinates: '%@', it should contains two comma seperated double values", gpsCoordinates);
warn about the 0 in the coordinates

2022-02-10 14:47 UTC, ArtursKadikis commented on ios/Classes/CountlyFlutterPlugin.m
> +                            COUNTLY_FLUTTER_LOG(@"Invalid location Coordinates: '%@', it should contains two comma seperated double values", gpsCoordinates);
"One of the values parsed to a 0, double check that given coordinates are correct:[$coordinates]."

2022-02-10 14:49 UTC, ArtursKadikis commented
Tweak the init time data structure

2022-02-16 10:46 UTC, ArtursKadikis requested changes
Let's prefix the location fields/entries with "location".
Pull out the ios location value checking into a separate function.

2022-02-22 13:43 UTC, merged